### ISSUE TITLE
PHP 8.0 support

### ISSUE THREAD

**Issue by boesing** [laminas-api-tools/api-tools-skeleton#26]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

To be prepared for the december release of PHP 8.0, this repository has some additional TODOs to be tested against the new major version.

In order to make this repository compatible, one has to follow these steps:

- [ ] Modify `composer.json` to provide support for PHP 8.0 by adding the constraint `~8.0.0`
- [ ] Modify `composer.json` to drop support for PHP less than 7.3
- [ ] Modify `composer.json` to implement phpunit 9.3 which supports PHP 7.3+
- [ ] Modify `.travis.yml` to ignore platform requirements when installing composer dependencies (simply add `--ignore-platform-reqs` to `COMPOSER_ARGS` env variable)
- [ ] Modify `.travis.yml` to add PHP 8.0 to the matrix (*NOTE*: Do not allow failures as PHP 8.0 has a feature freeze since 2020-08-04!)
- [ ] Modify source code in case there are incompatibilities with PHP 8.0

**Comment by stojanovicdusan** [comment]
It is not possible to do it until all other required dependency is updated to PHP 8.0.

**Comment by boesing** [comment]
Not 100% sure but PHP 8 has `--ignore-platform-req=php` set in github action.
Bit I dont think that this package is already migrated to GHA.

@weierophinney Do we have ignore platform req enabled?

**Comment by boesing** [comment]
Yup, here you go https://github.com/laminas/laminas-continuous-integration-action/blob/92f18a56222df7f3d1896de178b6c0531c1af5a0/entrypoint.sh#L82

Thus, you can still create a PR which supports PHP 8.0 for this specific package. No need to have the whole dependency tree verified just to see if there are TODOs in this package.

**Comment by boesing** [comment]
@stojanovicdusan I've prepared this repository so you can create a PR for PHP 8.0 with the instructions in this issue 👍🏼
