### ISSUE TITLE
Using composer create-project fails with Composer 2

### ISSUE THREAD

**Issue by taisph** [laminas-api-tools/api-tools-skeleton#28]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

Support for `composer create-project laminas-api-tools/api-tools-skeleton` using Composer 2. It currently fails during dependency installation with the error below.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laminas/laminas-component-installer 1.1.1 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - laminas/laminas-component-installer[2.1.1, ..., 2.3.2] require php ^7.1 -> your php version (5.6.40) does not satisfy that requirement.
    - Root composer.json requires laminas/laminas-component-installer ^1.1.1 || ^2.1.1 -> satisfiable by laminas/laminas-component-installer[1.1.1, 2.1.1, ..., 2.3.2].

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.
```

**Comment by rieschl** [comment]
> ```
>     - laminas/laminas-component-installer[2.1.1, ..., 2.3.2] require php ^7.1 -> your php version (5.6.40) does not satisfy that requirement.
> ```

`laminas-component-installer` supports composer 2 but requires at least PHP 7.1. you are using 5.6, so just use a current php Version :-)

**Comment by taisph** [comment]
> `laminas-component-installer` supports composer 2 but requires at least PHP 7.1. you are using 5.6, so just use a current php Version :-)

:man_facepalming: Nice catch. I've been jumping back and forth between PHP versions due to maintaining a large legacy stack.
