### ISSUE TITLE
Dockerfile PHP version mismatching composer.json PHP version

### ISSUE THREAD

**Issue by karnaf** [laminas-api-tools/api-tools-skeleton#32]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.6.x

#### Summary

Dockerfile uses php:**7.2**-apache but composer.json requires "php": "^**7.3**",

#### Current behavior

When installing the skeleton project and trying to update composer fails with problems because the PHP versions do not match

    root@315312c95fec:/var/www# composer update
    Loading composer repositories with package information
    Updating dependencies
    Your requirements could not be resolved to an installable set of packages.
      Problem 1
        - Root composer.json requires php ^7.3 but your php version (7.2.34) does not satisfy that requirement.
      Problem 2
        - phpunit/phpunit[9.5.0, ..., 9.5.4] require php >=7.3 -> your php version (7.2.34) does not satisfy that requirement.
        - Root composer.json requires phpunit/phpunit ^9.5 -> satisfiable by phpunit/phpunit[9.5.0, ..., 9.5.4].

#### How to reproduce
Download the ZIP version of the project - api-tools-skeleton-1.6.x.zip
Unsip the archive
Run `docker-compose up -d`
Access the container with `docker exec -it api-tools-skeleton-16x_apigility_1 /bin/bash`
Run `composer update`

#### Expected behavior
composer update to finish successfully

**Comment by Ocramius** [comment]
Handled in #39, although we really should move the docker PHP version to `8.1`.
