### ISSUE TITLE
Can't create project from composer

### ISSUE THREAD

**Issue by misterabdul** [laminas-api-tools/api-tools-skeleton#34]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.5.3

#### Summary

Can't create project using composer 2.0.12.

I've tried using `--stability dev` (stable, rc, beta, alpha as well) but the results are same.

#### Current behavior

```sh
$ composer create-project laminas-api-toos/api-tools-skeleton first_laminas
Creating a "laminas-api-toos/api-tools-skeleton" project at "./first_laminas"

In CreateProjectCommand.php line 394:
                                                                               
  Could not find package laminas-api-toos/api-tools-skeleton with stability stable.
```

#### How to reproduce

Just do `composer create-project laminas-api-toos/api-tools-skeleton` using the latest composer (currently I'm using 2.0.12)

#### Expected behavior

The project installed completely.

**Comment by froschdesign** [comment]
@misterabdul 
> `laminas-api-toos/api-tools-skeleton`

One letter is missing: `tools` instead of `toos`
