### ISSUE TITLE
Nginx Configuration Example

### ISSUE THREAD

**Issue by lewisstancer** [laminas-api-tools/api-tools-skeleton#46]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

An example Nginx configuration file would be handy, struggling to figure out the right spec to get this working. It appears Apace htaccess is doing something to rewrite the URL but for some reason I cannot figure it out. When I use the php -S command the ui works fine. When I point my Nginx config to the directory, I get 404 on /api-tools/ui

Seems like there is a web.config file for IIS but no Nginx config to be seen and no mention of it anywhere

**Comment by lewisstancer** [comment]
Bump

**Comment by Ocramius** [comment]
Closing here: please do send a patch, if you write one, but this will not be actively worked on by the maintainers of this project.
