### ISSUE TITLE
Error creating project from composer

### ISSUE THREAD

**Issue by gildonei** [laminas-api-tools/api-tools-skeleton#47]
### Bug Report

|    Software        |  Version
|------------ | ------
| Windows     | 11 - Full Updated
| PHP CLI | 7.4.9

#### Summary

Trying to create a new empty project according project tutorial in https://api-tools.getlaminas.org/

#### Current behavior

```
composer create-project laminas-api-tools/api-tools-skeleton
....

> php -r 'if (file_exists("src/remove-package-artifacts.php")) include "src/remove-package-artifacts.php";'
Script php -r 'if (file_exists("src/remove-package-artifacts.php")) include "src/remove-package-artifacts.php";' handling the post-create-project-cmd event returned with error code 1
```

#### How to reproduce

In console run `composer create-project laminas-api-tools/api-tools-skeleton`, and use production config files, at the end of process the line errors above will be displayed
![image](https://user-images.githubusercontent.com/1370979/152840651-503c147f-6a44-4782-8297-a31e1bfae3a8.png)

#### Expected behavior

Create a new project without errors

**Comment by Ocramius** [comment]
What happens if you run `php -r 'echo "hello";'` in your terminal? Wondering if the CLI tools are referencing the wrong `php` binary, perhaps :thinking:

**Comment by gildonei** [comment]
I am using Win 11 with Wampserver 3.2.3

My php executable is in my system variables pointing to "C:\wamp64\bin\php\php7.4.9"

```
D:\Sites\apigility>php -r 'echo "hello";'

Parse error: syntax error, unexpected ''echo' (T_ENCAPSED_AND_WHITESPACE), expecting end of file in Command line code on line 1
```

**Comment by gildonei** [comment]
```php
D:\Sites\apigility>php -v
PHP 7.4.9 (cli) (built: Aug  4 2020 11:52:41) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```

**Comment by Ocramius** [comment]
Something seems wrong about your system, IMO.

I'm unaware of how windows shell handles escaping, but over here:

```
~/Documents via ❄️  impure (nix-shell) 
❯ php -r 'echo "hello";'
hello
```

**Comment by gildonei** [comment]
In Windows you have to double quote

```
D:\Sites\apigility\html>php -r "echo \"Teste\";"
Teste
```

**Comment by gildonei** [comment]
> In Windows you have to double quote
> 
> ```
> D:\Sites\apigility\html>php -r "echo \"Teste\";"
> Teste
> ```

you can also use single quotes inside

```php
D:\Sites\apigility\html>php -r "echo 'Teste';"
Teste
```

**Comment by Ocramius** [comment]
I wonder if that's the same error that's happening in the installer plugin? What happens if you run it with something like cygwin or similar shells?

**Comment by gildonei** [comment]
Sorry, I can't reproduce it because I don't have a Linux instance running.

**Comment by gildonei** [comment]
I forked project and tried to install using git clone and composer install, and it was installed without errors, but, when I tried to create a new Api, it said Api was created but nothing changed.

**Comment by Ocramius** [comment]
Something like https://en.wikipedia.org/wiki/MinGW or https://en.wikipedia.org/wiki/Cygwin

**Comment by Ocramius** [comment]
Solved via:
 * #48 
 * #49
