### ISSUE TITLE
Remove zendframework-bridge 

### ISSUE THREAD

**Issue by boesing** [laminas-api-tools/api-tools-skeleton#54]
### Feature Removal

This component requires the `zendframework-bridge`.
Skeletons are meant to be used for fresh projects and fresh projects should not require this component at all.

https://github.com/laminas-api-tools/api-tools-skeleton/blob/0c63fe17a892de4602559301268a926ba4445d9c/composer.json#L38

**Comment by weierophinney** [comment]
Resolved with 86849a58
